=== ChanyMetal/hermes/hermes2d/include/mesh/mesh_h2d_xml.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="mesh_h2d">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="1" name="variables">
          <xs:complexType>
            <xs:sequence>
              <xs:element maxOccurs="unbounded" name="variable">
                <xs:complexType>
									<xs:attribute name="name" type="xs:string" use="required" />
									<xs:attribute name="value" type="xs:decimal" use="required" />
								</xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element minOccurs="1" maxOccurs="1" name="vertices">
          <xs:complexType>
            <xs:sequence>
              <xs:element minOccurs="3" maxOccurs="unbounded" name="vertex">
                <xs:complexType>
                  <xs:attribute name="x" type="xs:decimal" use="required" />
									<xs:attribute name="y" type="xs:decimal" use="required" />
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element minOccurs="1" maxOccurs="1" name="elements">
          <xs:complexType>
            <xs:sequence>
              <xs:choice minOccurs="1" maxOccurs="unbounded">
                <xs:element maxOccurs="unbounded" name="triangle">
                  <xs:complexType>
                    <xs:attribute name="v1" type="xs:integer" use="required" />
										<xs:attribute name="v2" type="xs:integer" use="required" />
										<xs:attribute name="v3" type="xs:integer" use="required" />										
										<xs:attribute name="marker" type="xs:string" use="required" />
                    <xs:attribute name="empty" type="xs:boolean" />
                  </xs:complexType>
                </xs:element>
								<xs:element maxOccurs="unbounded" name="quad">
                  <xs:complexType>
                    <xs:attribute name="v1" type="xs:integer" use="required" />
										<xs:attribute name="v2" type="xs:integer" use="required" />
										<xs:attribute name="v3" type="xs:integer" use="required" />
										<xs:attribute name="v4" type="xs:integer" use="required" />										
										<xs:attribute name="marker" type="xs:string" use="required" />
                    <xs:attribute name="empty" type="xs:boolean" />
                  </xs:complexType>
                </xs:element>
              </xs:choice>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element minOccurs="1" maxOccurs="1" name="boundaries">
          <xs:complexType>
            <xs:sequence>
              <xs:element maxOccurs="unbounded" name="boundary_edge">
                <xs:complexType>
                  <xs:attribute name="v1" type="xs:integer" use="required" />
									<xs:attribute name="v2" type="xs:integer" use="required" />										
									<xs:attribute name="marker" type="xs:string" use="required" />
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element maxOccurs="1" name="curves">
          <xs:complexType>
            <xs:sequence>
              <xs:element maxOccurs="unbounded" name="curve">
                <xs:complexType>
                  <xs:attribute name="v1" type="xs:integer" use="required" />
									<xs:attribute name="v2" type="xs:integer" use="required" />										
									<xs:attribute name="angle" type="xs:decimal" use="required" />
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== ChanyMetal/hermes/hermes2d/test_examples/1-03-poisson/domain.xml
<?xml version="1.0"?>

<mesh_h2d xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:noNamespaceSchemaLocation="../../include/mesh/mesh_h2d_xml.xsd">

  <variables>
    <variable name="a" value="1.0" />
    <variable name="m_a" value="-1.0" />
		<variable name="b" value="0.70710678118654757" />		
  </variables>

  <vertices>
    <vertex x="0" y="-1.0" />
		<vertex x="1.0" y="-1.0" />
		<vertex x="-1.0" y="0" />
		<vertex x="0" y="0" />
		<vertex x="1.0" y="0" />
		<vertex x="-1.0" y="1.0" />
		<vertex x="0" y="1.0" />
		<vertex x="0.70710678118654757" y="0.70710678118654757" />
  </vertices>

  <elements>
		<triangle v1="3" v2="4" v3="7" marker="Copper" />
		<triangle v1="3" v2="7" v3="6" marker="Aluminum" />
    <quad v1="0" v2="1" v3="4" v4="3" marker="Copper" />
		<quad v1="2" v2="3" v3="6" v4="5" marker="Aluminum" />
  </elements>

  <boundaries>
    <boundary_edge v1="0" v2="1" marker="Bottom" />
		<boundary_edge v1="1" v2="4" marker="Outer" />
		<boundary_edge v1="3" v2="0" marker="Inner" />
		<boundary_edge v1="4" v2="7" marker="Outer" />
		<boundary_edge v1="7" v2="6" marker="Outer" />
		<boundary_edge v1="2" v2="3" marker="Inner" />
		<boundary_edge v1="6" v2="5" marker="Outer" />
		<boundary_edge v1="5" v2="2" marker="Left" />
	</boundaries>

  <curves>
    <curve v1="4" v2="7" angle="45" />
		<curve v1="7" v2="6" angle="45" />
  </curves>
</mesh_h2d>

=== ChanyMetal/hermes/hermes2d/include/mesh/mesh_example_h2d.xml
<?xml version="1.0"?>

<mesh_h2d xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:noNamespaceSchemaLocation="../../include/mesh/mesh_h2d_xml.xsd">

  <variables>
    <variable>
      <name>a</name>
      <value>1.0</value>
    </variable>
    <variable>
      <name>-a</name>
      <value>-1.0</value>
    </variable>
    <variable>
      <name>b</name>
      <value>0.70710678118654757</value>
    </variable>
  </variables>

  <vertices>
    <vertex>
      <x> 0 </x>
      <y> -1.0 </y>
    </vertex>
    <vertex>
      <x> 1.0 </x>
      <y> -1.0 </y>
    </vertex>
    <vertex>
      <x> -1.0 </x>
      <y> 0 </y>
    </vertex>
    <vertex>
      <x> 0 </x>
      <y> 0 </y>
    </vertex>
    <vertex>
      <x> 1.0 </x>
      <y> 0 </y>
    </vertex>
    <vertex>
      <x> -1.0 </x>
      <y> 1.0 </y>
    </vertex>
    <vertex>
      <x> 0 </x>
      <y> 1.0 </y>
    </vertex>
    <vertex>
      <x> 0.70710678118654757 </x>
      <y> 0.70710678118654757 </y>
    </vertex>
  </vertices>

  <elements>
    <quad>
      <vertices>
        <vertex>
          0
        </vertex>
        <vertex>
          1
        </vertex>
        <vertex>
          4
        </vertex>
        <vertex>
          3
        </vertex>
      </vertices>
      <marker>
        Copper
      </marker>
    </quad>
    <triangle>
      <vertices>
        <vertex>
          3
        </vertex>
        <vertex>
          4
        </vertex>
        <vertex>
          7
        </vertex>
      </vertices>
      <marker>
        Copper
      </marker>
    </triangle>
    <triangle>
      <vertices>
        <vertex>
          3
        </vertex>
        <vertex>
          7
        </vertex>
        <vertex>
          6
        </vertex>
      </vertices>
      <marker>
        Aluminum
      </marker>
    </triangle>
    <quad>
      <vertices>
        <vertex>
          2
        </vertex>
        <vertex>
          3
        </vertex>
        <vertex>
          6
        </vertex>
        <vertex>
          5
        </vertex>
      </vertices>
      <marker>
        Aluminum
      </marker>
    </quad>
  </elements>

  <boundaries>
    <boundary_edge>
      <vertex>
        0
      </vertex>
      <vertex>
        1
      </vertex>
      <marker>
        Bottom
      </marker>
    </boundary_edge>
    <boundary_edge>
      <vertex>
        1
      </vertex>
      <vertex>
        4
      </vertex>
      <marker>
        Outer
      </marker>
    </boundary_edge>
    <boundary_edge>
      <vertex>
        3
      </vertex>
      <vertex>
        0
      </vertex>
      <marker>
        Inner
      </marker>
    </boundary_edge>
    <boundary_edge>
      <vertex>
        4
      </vertex>
      <vertex>
        7
      </vertex>
      <marker>
        Outer
      </marker>
    </boundary_edge>
    <boundary_edge>
      <vertex>
        7
      </vertex>
      <vertex>
        6
      </vertex>
      <marker>
        Outer
      </marker>
    </boundary_edge>
    <boundary_edge>
      <vertex>
        2
      </vertex>
      <vertex>
        3
      </vertex>
      <marker>
        Inner
      </marker>
    </boundary_edge>
    <boundary_edge>
      <vertex>
        6
      </vertex>
      <vertex>
        5
      </vertex>
      <marker>
        Outer
      </marker>
    </boundary_edge>
    <boundary_edge>
      <vertex>
        5
      </vertex>
      <vertex>
        2
      </vertex>
      <marker>
        Left
      </marker>
    </boundary_edge>
  </boundaries>

  <curves>
    <curve>
      <vertex>
        4
      </vertex>
      <vertex>
        7
      </vertex>
      <angle>
        45
      </angle>
    </curve>
    <curve>
      <vertex>
        7
      </vertex>
      <vertex>
        6
      </vertex>
      <angle>
        45
      </angle>
    </curve>
  </curves>
</mesh_h2d>
