=== ChanyMetal/hermes/hermes2d/include/mesh/subdomains_h2d_xml.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="domain_h2d">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="1" name="variables">
          <xs:complexType>
            <xs:sequence>
              <xs:element minOccurs="0" maxOccurs="unbounded" name="variable">
                <xs:complexType>
									<xs:attribute name="name" type="xs:string" use="required" />
									<xs:attribute name="value" type="xs:decimal" use="required" />
								</xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element minOccurs="1" maxOccurs="1" name="vertices">
          <xs:complexType>
            <xs:sequence>
              <xs:element minOccurs="3" maxOccurs="unbounded" name="vertex">
                <xs:complexType>
                  <xs:attribute name="x" type="xs:string" use="required" />
									<xs:attribute name="y" type="xs:string" use="required" />
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element minOccurs="1" maxOccurs="1" name="elements">
          <xs:complexType>
            <xs:sequence>
              <xs:choice minOccurs="1" maxOccurs="unbounded">
                <xs:element minOccurs="0" maxOccurs="unbounded" name="triangle">
                  <xs:complexType>
                    <xs:attribute name="v1" type="xs:integer" use="required" />
										<xs:attribute name="v2" type="xs:integer" use="required" />
										<xs:attribute name="v3" type="xs:integer" use="required" />										
										<xs:attribute name="marker" type="xs:string" use="required" />
                    <xs:attribute name="empty" type="xs:boolean" />
                  </xs:complexType>
                </xs:element>
								<xs:element minOccurs="0" maxOccurs="unbounded" name="quad">
                  <xs:complexType>
                    <xs:attribute name="v1" type="xs:integer" use="required" />
										<xs:attribute name="v2" type="xs:integer" use="required" />
										<xs:attribute name="v3" type="xs:integer" use="required" />
										<xs:attribute name="v4" type="xs:integer" use="required" />										
										<xs:attribute name="marker" type="xs:string" use="required" />
                    <xs:attribute name="empty" type="xs:boolean" />
                  </xs:complexType>
                </xs:element>
              </xs:choice>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element minOccurs="1" maxOccurs="1" name="boundaries">
          <xs:complexType>
            <xs:sequence>
              <xs:element minOccurs="0" maxOccurs="unbounded" name="boundary_edge">
                <xs:complexType>
                  <xs:attribute name="v1" type="xs:integer" use="required" />
									<xs:attribute name="v2" type="xs:integer" use="required" />										
									<xs:attribute name="marker" type="xs:string" use="required" />
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
				<xs:element minOccurs="0" maxOccurs="1" name="curves">
					<xs:complexType>
            <xs:sequence>
						  <xs:choice>
								<xs:element minOccurs="0" maxOccurs="unbounded" name="arc">
									<xs:complexType>
										<xs:attribute name="v1" type="xs:integer" use="required" />
										<xs:attribute name="v2" type="xs:integer" use="required" />	
										<xs:attribute name="angle" type="xs:decimal" use="required" />
									</xs:complexType>
								</xs:element>
								<xs:element minOccurs="0" maxOccurs="unbounded" name="NURBS">
									<xs:complexType mixed="true">
										<xs:sequence>
											<xs:element minOccurs="0" maxOccurs="unbounded" name="inner_point">
												<xs:complexType>
													<xs:attribute name="x" type="xs:decimal" use="required" />
													<xs:attribute name="y" type="xs:decimal" use="required" />	
													<xs:attribute name="weight" type="xs:decimal" use="required" />
												</xs:complexType>
											</xs:element> 
											<xs:element minOccurs="0" maxOccurs="unbounded" name="knot">
												<xs:complexType>
													<xs:attribute name="value" type="xs:decimal" use="required" />
												</xs:complexType>
											</xs:element>
										</xs:sequence>
										<xs:attribute name="v1" type="xs:integer" use="required" />
										<xs:attribute name="v2" type="xs:integer" use="required" />	
										<xs:attribute name="degree" type="xs:integer" use="required" />
									</xs:complexType>
								</xs:element>
							</xs:choice>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
				<xs:element name="subdomains">
					<xs:complexType>
						<xs:sequence>
							<xs:element minOccurs="1" maxOccurs="unbounded" name="subdomain">
								<xs:complexType mixed="true">
									<xs:sequence>
										<xs:element minOccurs="0" maxOccurs="unbounded" name="element-number">
											<xs:complexType>
												<xs:attribute name="number" type="xs:integer" use="required" />
											</xs:complexType>
										</xs:element> 
										<xs:element minOccurs="0" maxOccurs="unbounded" name="boundary_edge-number">
											<xs:complexType>
												<xs:attribute name="number" type="xs:integer" use="required" />
											</xs:complexType>
										</xs:element>
									</xs:sequence>
									<xs:attribute name="name" type="xs:string" use="required" />
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== ChanyMetal/hermes/hermes2d/include/mesh/subdomains_h2d_xml_example.xml
<?xml version="1.0"?>

<domain_h2d xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:noNamespaceSchemaLocation="subdomains_h2d_xml.xsd">

  <variables>
    <variable name="a" value="1.0" />
    <variable name="two_a" value="2.0" />
  </variables>

  <vertices>
    <vertex x="0" y="0" />
		<vertex x="a" y="0" />
		<vertex x="two_a" y="0" />
		<vertex x="two_a" y="a" />
		<vertex x="two_a" y="two_a" />
		<vertex x="a" y="two_a" />
		<vertex x="0" y="two_a" />
		<vertex x="0" y="a" />
		<vertex x="a" y="a" />
  </vertices>

  <elements>
		<quad v1="0" v2="1" v3="8" v4="7" marker="Bottom Left" />
		<quad v1="1" v2="2" v3="3" v4="8" marker="Bottom Right" />
		<quad v1="8" v2="3" v3="4" v4="5" marker="Top Right" />
		<quad v1="7" v2="8" v3="5" v4="6" marker="Top Left" />
  </elements>

  <boundaries>
    <boundary_edge v1="0" v2="1" marker="Bottom Left" />
		<boundary_edge v1="1" v2="2" marker="Bottom Right" />
		
		<boundary_edge v1="2" v2="3" marker="Bottom Right" />
		<boundary_edge v1="3" v2="4" marker="Top Right" />
		
		<boundary_edge v1="4" v2="5" marker="Top Right" />
		<boundary_edge v1="5" v2="6" marker="Top left" />
		
		<boundary_edge v1="6" v2="7" marker="Top Left" />
		<boundary_edge v1="7" v2="0" marker="BottomLeft" />
		
		<boundary_edge v1="1" v2="8" marker="Vertical Bottom" />
		<boundary_edge v1="8" v2="1" marker="Vertical Bottom" />
		<boundary_edge v1="8" v2="5" marker="Vertical Top" />
		<boundary_edge v1="5" v2="8" marker="Vertical Top" />
		
		<boundary_edge v1="7" v2="8" marker="Horizontal Left" />
		<boundary_edge v1="8" v2="7" marker="Horizontal Left" />
		<boundary_edge v1="8" v2="3" marker="Horizontal Right" />
		<boundary_edge v1="3" v2="8" marker="Horizontal Right" />
	</boundaries>
	
	<subdomains>
		<subdomain name="Whole domain" />
		<subdomain name="Bottom Left Corner" >
			<element-number number="0" />
			<boundary_edge-number number="0" />
			<boundary_edge-number number="8" />
			<boundary_edge-number number="13" />
			<boundary_edge-number number="7" />
		</subdomain>
		<subdomain name="Supplement of Bottom Left Corner">
			<element-number number="1" />
			<element-number number="2" />
			<element-number number="3" />
			<boundary_edge-number number="1" />
			<boundary_edge-number number="2" />
			<boundary_edge-number number="3" />
			<boundary_edge-number number="4" />
			<boundary_edge-number number="5" />
			<boundary_edge-number number="6" />
			<boundary_edge-number number="12" />
			<boundary_edge-number number="9" />
		</subdomain>
	</subdomains>
</domain_h2d>
